### ISSUE TITLE
mdBook has a CVE

### ISSUE THREAD

**Issue by nisrulz** [Dhghomon/easy_rust#104]
![Screenshot from 2021-01-04 16-37-40](https://user-images.githubusercontent.com/2096087/103551872-480b3400-4eab-11eb-8024-f5fe95d7dd86.png)

https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html

**Comment by Dhghomon** [comment]
Thanks! I'll ping @FongYoong about it.

**Comment by FongYoong** [comment]
@nisrulz Thanks for pointing out this issue. As you all may be aware, the Github Action's workflow depends on [peaceiris/actions-mdbook](https://github.com/peaceiris/actions-mdbook#%EF%B8%8F-use-the-latest-version-of-mdbook) for building MdBook. From the given link, we see the following:

![image](https://user-images.githubusercontent.com/50460394/103558217-482d2300-4eef-11eb-97ed-32b17c2d29d7.png)
***
The [mdbook — Homebrew Formulae](https://formulae.brew.sh/formula/mdbook) link leads us to the details shown below:

![image](https://user-images.githubusercontent.com/50460394/103558394-8e828200-4eef-11eb-9add-964444ccc817.png)

Clearly, the MdBook version (0.4.4) is outdated even though it's supposed to be up-to-date. We dig further by checking out the [Formula code](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mdbook.rb) link which is the source of the Homebrew package:

![image](https://user-images.githubusercontent.com/50460394/103558878-47e15780-4ef0-11eb-98eb-50c01c536dc8.png)

From the above, it is now obvious why the package is outdated—i.e., the Ruby script itself is outdated!
A [pull request](https://github.com/Homebrew/homebrew-core/pull/68255/files) has already been made for that repo to update the links to 0.4.5. So unfortunately, we'll have to wait for the moderators of that repo to approve the PR.
Well, I hope you don't mind, @Dhghomon. It's a silent risk we partake in when relying on open source tools.

**Comment by Dhghomon** [comment]
Sure, I assume it won't take long in any case - looks like the PR there is only 2 hours old. Thanks for taking a look!

**Comment by FongYoong** [comment]
![image](https://user-images.githubusercontent.com/50460394/103606801-4c3e5c80-4f52-11eb-8a28-b8dd2d871ca4.png)

The [latest build](https://github.com/Dhghomon/easy_rust/runs/1647581940?check_suite_focus=true) has been updated to 0.4.5 as shown above, so you can close this issue @Dhghomon.

**Comment by Dhghomon** [comment]
Will do!
