### ISSUE TITLE
const and static -> why do we need them?

### ISSUE THREAD

**Issue by hoijui** [Dhghomon/easy_rust#115]
regarding this section:
https://github.com/Dhghomon/easy_rust#const-and-static

```
There are two types that don't use let to declare: const and static.
```
This is a bit confusing to me.. are they really types?
and if not, why are they needed, given that `let` without `mut` is also constant?

**Comment by hoijui** [comment]
btw.... reaaally great thing, your _easy_rust_, thank you!
I have seen quite some things already, and this is what I like the most for learning rust so far. :-)

**Comment by Dhghomon** [comment]
Glad you like it!

I guess I should have said "ways to declare" or something like that (not types) - I'm bad at being precise with terminology. I think I'll change that.

One quick difference is that you can't shadow a const so this won't work:

```
const WORD: &str = "word";

fn main() {
    let WORD = "Some other word";
}
```

Also a const can be declared (and is usually declared) outside of all code blocks so it lives throughout the program - you can't use `let` outside of them. I should probably add that info too.

So this won't work:

```
let word = "word"; // This part won't work

fn main() {
    const WORD: &str = "word"; // But this is okay, though it's kind of weird in most cases to put a const here
}
```

**Comment by hoijui** [comment]
ahhhh perfect! :-)
yeah please! those 3 things would make it perfect!

**Comment by xsandr** [comment]
I have another suggestion regarding this section,

> static is a value that does not change and has a fixed memory location.

This is slightly imprecise, since static variable might be changed or reassigned using `static mut` declaration. But it makes access to the static variable unsafe

**Comment by Dhghomon** [comment]
Thanks! True but tough to introduce (at least here in the beginning) as part of the idea of the book is to not have people rage quit Rust. Could add that point nearer to the end when the reader/viewer is well used to complexity and new things.

**Comment by Dhghomon** [comment]
Also the book doesn't even introduce the unsafe keyword at all. (Though I ended up mentioning it in the videos) Hmmm

**Comment by Dhghomon** [comment]
Resolved now here: https://github.com/Dhghomon/easy_rust/pull/129
