### ISSUE TITLE
@ can be used without the value

### ISSUE THREAD

**Issue by mcastorina** [Dhghomon/easy_rust#12]
> And when you use @, you have to use the value. It will give an error if you don't:

> error: 1 positional argument in format string, but no arguments were given
 --> src\main.rs:4:30
  |
4 |     number @ 13 => println!("{} is unlucky in North America, lucky in Italy! In bocca al lupo!"),

The provided error is because you used `{}` without a positional argument.

This works perfectly fine:

```rust
fn match_number(input: i32) {
    match input {
    number @ 4 => println!("{} is an unlucky number in China (sounds close to 死)!", number),
    number @ 13 => println!("thirteen is unlucky in North America, lucky in Italy! In bocca al lupo!"),
    _ => println!("Looks like a normal number"),
    }
}

fn main() {
    match_number(13);
}
```

```
thirteen is unlucky in North America, lucky in Italy! In bocca al lupo!
```

**Comment by Dhghomon** [comment]
Good eye @mcastorina, thanks - I've deleted that part.
