### ISSUE TITLE
Incorrect terminology in 'Implementing structs and enums'

### ISSUE THREAD

**Issue by pie-flavor** [Dhghomon/easy_rust#132]
The chapter calls everything in an `impl` block 'methods', and functions that don't take self 'associated methods or static methods'. This is incorrect terminology according to the Book, the Reference, etc. It should be that everything in an `impl` block is 'associated functions', everything specifically in an `impl Foo` block as opposed to a trait impl 'inherent functions', and functions with a self parameter 'methods'. 'Static methods' is entirely Java terminology; you wouldn't use it for the same reason you don't call structs classes.

**Comment by Dhghomon** [comment]
Hm, I've never learned Java so it's definitely not influence from there. Here for example they are also called static methods (that's probably where it entered my head):

https://doc.rust-lang.org/rust-by-example/fn/methods.html

But yeah, associated function is the right term to use.

**Comment by pie-flavor** [comment]
Aha. It seems that language dates to pre-1.0 when that actually was the name, and nobody's ever updated it. (Doc stagnation: one of the many reasons I tend to recommend against RBE.)
