### ISSUE TITLE
"LOWERCASE" error in "Taking User Input"?

### ISSUE THREAD

**Issue by markcharney** [Dhghomon/easy_rust#135]
Hi. New to rust so maybe I'm wrong... I tried the example in "Taking User Input" where you use "cargo run LOWERCASE Does this work too?" and it did not convert "Does" to lower case, as shown in the book online here:  https://dhghomon.github.io/easy_rust/Chapter_63.html  ... If "LOWERCASE" matched "lowercase" in the "match" , it would imply that that match on a string would be case insensitive.  I think you just need to change "LOWERCASE" to "lowercase" in the example run.

**Comment by Dhghomon** [comment]
Good eye! Yeah, that part shouldn't be uppercase - fixed now.

**Comment by Dhghomon** [comment]
By the way (since you're new to Rust) it would be easy to [make the input lowercase](https://doc.rust-lang.org/std/primitive.str.html#method.to_lowercase) before matching but we'll just assume here that the user isn't having their hand held so looks good as is with your fix.
