### ISSUE TITLE
section on arrays in the tour of the standard library is outdated

### ISSUE THREAD

**Issue by danj** [Dhghomon/easy_rust#141]
The explanation is no longer valid as the following code works fine
The array implements the IntoIterator trait, and the for loop results in an implicit call to .into_iter().

```
fn main() {
    // ⚠️
    let my_cities = ["Beirut", "Tel Aviv", "Nicosia"];

    for city in my_cities {
        println!("{}", city);
    }
}
```

**Comment by Dhghomon** [comment]
Done! (And only six months late)
