### ISSUE TITLE
Animal, not AnimalType

### ISSUE THREAD

**Issue by egueler** [Dhghomon/easy_rust#21]
Love the tutorial! This is my introduction to Rust, so thank you!

In the section "[Implementing structs and enums](https://github.com/Dhghomon/easy_rust#implementing-structs-and-enums)" it says that Self means AnimalType. This point is repeated a few times in this section and the following. But if I'm not completely mistaken, isn't Self = Animal instead of AnimalType?

**Comment by sudo-nice** [comment]
`Self` in the context of `Animal` definitely returns `Animal`, not `AnimalType`, as you can see below:

```rust
#[derive(Debug)]
enum AnimalType {
    Cat,
}

#[derive(Debug)]
struct Animal {
    age: u8,
    animal_type: AnimalType,
}

impl Animal {
    fn new() -> Self {
        Self {
            age: 10,
            animal_type: AnimalType::Cat,
        }
    }
}

fn main() {
    let animal = Animal::new();
    println!("{:?}", animal); // Animal { age: 10, animal_type: Cat }
}
```

It looks like the manual is misleading.
