### ISSUE TITLE
Introduce the inclusive range at the same time as the exclusive one, for clarity.

### ISSUE THREAD

**Issue by joseluis** [Dhghomon/easy_rust#3]
In the Arrays section the range syntax is explained, but only the exclusive one (`..`), not the inclusive (`..=`):
[`* Index ranges are exclusive (they do not include the last number)`](https://github.com/Dhghomon/easy_rust/blame/master/README.md#L1363)

It is later used in an example in Enums section without an explicit explanation (and before that it shows in compiler output):
[`        6..=18 => ThingsInTheSky::Sun, // Between 6 and 18 hours we can see the sun`](https://github.com/Dhghomon/easy_rust/blame/master/README.md#L1877)

The inclusive syntax is not properly explained until Loops:
[` * ..= creates an inclusive range: 0..=3 = 0, 1, 2, 3.`](https://github.com/Dhghomon/easy_rust/blame/master/README.md#L2232)

I think it may be clearer to have it both options layed out the first time. or at least link to the full explanation from there. Because right now it kind of gives the impression that ranges for Arrays can not ever be inclusive.

**Comment by Dhghomon** [comment]
Thanks, @joseluis - this is going to be the trickiest part and it's nice to have some extra eyes to help out. I just added the inclusive syntax to the section on arrays.
