### ISSUE TITLE
Replacing "incomplete snippet" etc. with emojis

### ISSUE THREAD

**Issue by Dhghomon** [Dhghomon/easy_rust#38]
@AlexanderWillner The thought just occurred to me that the (Note: this will not compile) and "incomplete code snippet" notations could each be replaced with an emoji to improve readability and keep new users from being distracted when reading the code samples. Would that work with the script you've made though? I was thinking of these two:

🚧
https://unicode.org/emoji/charts/full-emoji-list.html#1f6a7 

⁉
https://unicode.org/emoji/charts/full-emoji-list.html#2049

The first is for the incomplete code snippets, and the second for code that needs a fix to compile, and of course they could be put together as well for code that matches both. Then all I would need to do is add a quick explanation at the beginning of the book in the same way that the Rust Book does with the crab images they use to give a hint that the code won't work.

**Comment by AlexanderWillner** [comment]
Yes, this would work.

**Comment by Arcadie** [comment]
Maybe it's a good idea to support multiple strings for the ignore argument?

Please take a look at this: https://github.com/AlexanderWillner/md2src/pull/1

This way, we could have snippets like:

```rust
// ⚠️ compilation error:
...
```

and 

```rust
// 🚧 fragment
...
```

and run the command line program with: `md2src README.md -i '// ⚠️ compilation error:' -i '// 🚧 fragment'`

What do you think?

**Comment by Dhghomon** [comment]
@Arcadie I do like the two symbols (⚠️ or the other `?!` one I thought of) but I'd prefer just having the symbols and no text. Basically the same thing as the Rust Book here: https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html (skip to "Comparing the Guess to the Secret Number") where Ferris shows you that it won't compile without needing to add any text.

**Comment by Dhghomon** [comment]
Assuming that I understood you correctly, of course - let me know if I misinterpreted what you wrote.

**Comment by Arcadie** [comment]
Sure, emoji-ony should work as expected:

```rust
fn main() {
    println!("This will be a snippet that will be checked by the compiler");
}
```

```rust
🚧
fn main() {
    println!("This one will be ignored!");
}
```

```rust
⁉
fn main() {
    println!("This one will be ignored as well!");
}
```

Change `md2src` command to:

```
md2src examples/emoji.md -i '🚧' -i '⁉'
```

Output:

Only one snippet file:

```rust
fn main() {
    println!("This will be a snippet that will be checked by the compiler");
}
```

**Comment by Dhghomon** [comment]
Great, looks good. Actually I think I'll go with your ⚠️ idea because the !? looks too much like regular text at times. I'm just writing about attributes and how traits like Display can't be automatically derived so I'll be able to put it together like this:

```rust
// ⚠️
#[derive(Display)]   
struct HoldsAString {
    the_string: String,
}
```

I was first leaning towards  // ⚠️ to the right of the first line of every such snippet but then it included it in the error message:

```text
error: cannot find derive macro `Display` in this scope
 --> src\main.rs:1:10
  |
1 | #[derive(Display)]   // ⚠️
  |          ^^^^^^^
```

So maybe putting it just above is the way to go.

**Comment by Arcadie** [comment]
Great! Just FYI, it depends on [this pull request](https://github.com/AlexanderWillner/md2src/pull/1) getting through and a new version of md2src being published. Other that that, happy to help 😄

**Comment by Dhghomon** [comment]
Okay! Merging now.

**Comment by AlexanderWillner** [comment]
@Arcadie new version of ms2src has been published, so you can now create a new pull request

**Comment by Arcadie** [comment]
Cool, thanks! Pull request: https://github.com/Dhghomon/easy_rust/pull/39

**Comment by Arcadie** [comment]
Please note that I did not go through each snippet to place them at the start, there are just too many for me to edit manually. ☹️

But they do look nice either way:

<img width="598" alt="screenshot" src="https://user-images.githubusercontent.com/1472875/88843633-21551d00-d1ea-11ea-918a-e484f03943b0.png">

**Comment by Dhghomon** [comment]
All done! Thanks all and closing now.
