### ISSUE TITLE
Consistently style traits with italics

### ISSUE THREAD

**Issue by sudo-nice** [Dhghomon/easy_rust#5]
I think, we can make traits more stand out throughout the doc by applying some consistent style to it. I was thinking about using italics, if you had no plans for that style already. Now the traits are sometimes bold and sometimes just a plain text. Using italics would make lines like:

String is not Copy, so my_closure() is Fn: it takes a reference.
You can see for example **Copy**, **Debug**, and **Display**.

...to look like:

String is not _Copy_, so my_closure() is Fn: it takes a reference.
You can see for example _Copy_, _Debug_, and _Display_.

What do you think?

**Comment by pretzelhammer** [comment]
I think all code should be styled using ``. Italics imply emphasis but there's no reason to randomly emphasis trait names. Trait names are code and should be styled as code, i.e. `Copy` is just shorthand for `std::marker::Copy`, `Debug` is shorthand for `std::fmt::Debug`, and so on.

**Comment by stappersg** [comment]
Yes, `code` should be styled as `code`.

**Comment by sudo-nice** [comment]
Ok, closing then.
