### ISSUE TITLE
Using ```code``` for inlined code chunks

### ISSUE THREAD

**Issue by sudo-nice** [Dhghomon/easy_rust#7]
I see you use triple backticks (\`\`\`code\`\`\`) style for inlined code as well. Is there a specific reason for that? Because I'm going to open some PRs and I wonder if it's Ok to use single backticks (\`code\`) for that?
I can convert all the triplets to the single ones where appropriate, for the sake of consistency, if you'd like.

**Comment by Dhghomon** [comment]
Ooh, that would have been good to know. No, I didn't know you could do that. Let's check: `let backtick_test = 0;`

**Comment by sudo-nice** [comment]
If you were going to convert it for yourself, please wait. I have another PR coming which would be better to merge first.

**Comment by Dhghomon** [comment]
Okay. No, I was in no rush to do so. I'm a bit of a slacker when it comes to proper or optimized format and tend to do that at the very, very end.

**Comment by sudo-nice** [comment]
Oh, I see, for for the early trouble then.
The PR I was talking about is ready. I'll take a break for you to concentrate on the content instead of formatting.

**Comment by sudo-nice** [comment]
But let me know if you'd like me to convert the triplets anyway.

**Comment by Dhghomon** [comment]
Sure! I always welcome formatting corrections.

**Comment by sudo-nice** [comment]
I've just realized you were new to Github, so maybe you'd find this Markdown [cheatsheet] interesting.

[cheatsheet]: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
