### ISSUE TITLE
"国" is a Chinese character

### ISSUE THREAD

**Issue by ngolin** [Dhghomon/easy_rust#71]
The author says "国" is a Japanese character, which may confuse the Chinese readers.

**Comment by Dhghomon** [comment]
This was already discussed before - please see the PR.

**Comment by ngolin** [comment]
https://github.com/Dhghomon/easy_rust/pull/45

Yes, I understand your point. Can we pick another Japanese character, which is unique to Japanese, such as "の" or others with good meaning?

**Comment by Dhghomon** [comment]
@ngolin Japanese doesn't mean **exclusively** Japanese any more than something like "the English word **nation** / **bazaar** / **piano**" implies that it's exclusive to English and doesn't come from French / Persian / Italian.

**Comment by ngolin** [comment]
Yes, I understand your point. And maybe pick another Japanese character would be a better solution and a gread kindness. Can I pull a request to do that? Thank you for the great book 😃 @Dhghomon

**Comment by Dhghomon** [comment]
Thanks, I'm glad you like the book! I still won't take a pull request though - I'm fairly stubborn on this. 😃

**Comment by Dhghomon** [comment]
@ngolin Video here by the way if you are curious: https://www.youtube.com/watch?v=jc1UvlBnKRw

**Comment by ngolin** [comment]
Okay, thanks for your consideration. I just want to remind you it might hurt feelings.

**Comment by ngolin** [comment]
@Dhghomon Thank you, respect.

**Comment by Dhghomon** [comment]
Feelings should be fine - don't forget about this part:

>Characters in Rust are called char. Every char has a number: the letter A is number 65, while the character 友 ("friend" in **Chinese**) is number 21451. The list of numbers is called "Unicode". Unicode uses smaller numbers for characters that are used more, like A through Z, or digits 0 through 9, or space.

**Comment by ngolin** [comment]
Yes, I read this part! The problem is not many Chinese know "国" is a Japanese character too.

**Comment by Dhghomon** [comment]
@ngolin Could be a good reminder then of how influential China was throughout its history. The more you know 🌠
