### ISSUE TITLE
Code examples in "Option" chapter

### ISSUE THREAD

**Issue by UweSauter** [Dhghomon/easy_rust#79]
Hi,

most examples in the "Option" chapter are wrong. The second example contains `if value.len() < 5` and is correct, the following examples contain `if value.len() < 4` and don't catch the case where `value.len() == 4`. In all examples you access `value[4]` in the `else` branch.

Regards,

Uwe

**Comment by Dhghomon** [comment]
Thanks, resolved now here: https://github.com/Dhghomon/easy_rust/pull/129
