### ISSUE TITLE
Char type in chapter Types -> Primitive types

### ISSUE THREAD

**Issue by UweSauter** [Dhghomon/easy_rust#80]
Hi,

this sentence confuses me:
`All chars are 4 bytes. They are 4 bytes because some characters in a string are more than one byte. Basic letters that have always been on computers are 1 byte, later characters are 2 bytes, and others are 3 and 4. A char needs to be 4 bytes so that it can hold any kind of character.`

It would probably better to rephrase

`All chars take 4 byte in memory so they can represent all Unicode elements. Basic letters will only take 1 byte out of the available 4 bytes, other letters like German Umlauts will require 2 bytes and e.g. Korean, Japanese or Chinese signs will require 3 or all 4 bytes.`
`Strings on the other hand are encoded in UTF-8 and thus use the minimal memory footprint required to hold the letters in the string.`

Also the example does not show what I think is intended:
```
fn main() {
    println!("{}", "a".len()); // .len() gives the size in bytes
    println!("{}", "ß".len());
    println!("{}", "国".len());
    println!("{}", "𓅱".len());
}
```
If it should show the size of the chars, the output should always be "4" and the example should use single apostrophes `'`. But that would not compile because the `char` type does not have a `len()` method.

What it actually shows is the length of the UFT-8 encoded string. Which is a significant difference to the length of a `char`, which is always 4.

You might want to change the code example to:
```
fn main() {
    println!("Size of a char: {}", std::mem::size_of::<char>());
    println!("Size of string containing 'a': {}", "a".len()); // .len() gives the size in bytes
    println!("Size of string containing 'ß': {}", "ß".len());
    println!("Size of string containing '国': {}", "国".len());
    println!("Size of string containing '𓅱': {}", "𓅱".len());
}
```

Regards,

Uwe

**Comment by Dhghomon** [comment]
Thanks, resolved now here: https://github.com/Dhghomon/easy_rust/pull/129
