### ISSUE TITLE
Chapter "RwLock"

### ISSUE THREAD

**Issue by UweSauter** [Dhghomon/easy_rust#82]
Hi,

in chapter "RwLock" you list the rules applying to a RwLock variable:

1. many `.read()` variables is okay,
2. one `.write()` variable is okay,
3. but more than one `.read()` or `.read()` together with `.write()` is not okay.

I think rule 3 should read: but more than one `.write()` or `.read()` together with `.write()` is not okay.

Regards,

Uwe

**Comment by Dhghomon** [comment]
Thanks, looks like this one's resolved now.
