### ISSUE TITLE
Chapter "Taking user input"

### ISSUE THREAD

**Issue by UweSauter** [Dhghomon/easy_rust#84]
Hi,

at the end of chapter "Taking user input" you explain how to access environment variables which looks good to me until you introduce the `env!` macro.

As environment variables are usually queried while the program is run and not while it is compiled, I think that the last section (beginning with the sentence "The easiest way to get a single Var is by using the env! macro.") is actually not what you are trying to show.

From the Rust documentation {1}:
```
Macro std::env
Inspects an environment variable at compile time.
```
The same applies to the `option_env!` macro (which you incorrectly call `option_str!` twice in the text but use correctly in the code example).

If you really want to show how environment variables can be checked while compilation then this should be made clear in the text.

Regards,

Uwe

[1] https://doc.rust-lang.org/std/macro.env.html

**Comment by Dhghomon** [comment]
Thanks, resolved now here: https://github.com/Dhghomon/easy_rust/pull/129
