### ISSUE TITLE
Chapter "Using files"

### ISSUE THREAD

**Issue by UweSauter** [Dhghomon/easy_rust#85]
Hi,

some things that caught my eye in the "using files" chapter:

1. The second version of the first code example returns `Ok(88)` and `Ok(5)` which is correct, yet you state: "The first one doesn't work, but the second one does." I don't know what you're trying to say here.
2. There's a type with apostrophe and backtick in the sentence "So it is a Result<T, Error>', but we only need to write the Result` part."
3. The comment in the first file example code is wrong: `std::fs::File::create` will not delete a file that already exists, it will only delete the content (truncate). This is an important distinction because the file system entry of the file does not change, only the size does.
4. The same applies to `std::fs::write`: it will only remove the content of an already existing file, not the file itself.

Thanks for your effort in creating Rust in Easy English.

Regards,

Uwe

**Comment by Dhghomon** [comment]
Thanks, resolved now here: https://github.com/Dhghomon/easy_rust/pull/129
