### ISSUE TITLE
[Typo] Milliseconds instead of microseconds

### ISSUE THREAD

**Issue by Andrflor** [Dhghomon/easy_rust#87]
At the end of the readme it says:
-------------------------------------------------------

```text
1.025µs
683.378µs
```

So that's just over 1 microsecond vs. 683 milliseconds. We can see that Rust did take some time to do it.

----------------------------------------------------------

This is 683 microseconds not milliseconds.
Just a little typo ahah, thx for the good work :smiley:

**Comment by Dhghomon** [comment]
Thanks, looks like this one's resolved now.
